server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/instagram
    username: root
    password: 09102004phuc
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: Asgard
      password: 09102004
  #    oauth2:
  #        client:
  #            registration:
  #              google:
  #                client-id: ${GOOGLE_CLIENT_ID}
  #                client-secret: ${GOOGLE_CLIENT_SECRET}
  #              facebook:
  #                client-id: ${FACEBOOK_CLIENT_ID}
  #                client-secret: ${FACEBOOK_CLIENT_SECRET}
# Logging configuration
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.cors: DEBUG
app:
  jwt:
    secret: ${JWT_SECRET:defaultSecretKeyWhichShouldBeVeryLongAndSecure}
    expiration: 86400000
  # File upload configuration
  file:
    upload-dir: ./uploads
